apiVersion: v1
kind: ServiceAccount
metadata:
  name: gketenant-trial-mumbai-01-users-sa
  namespace: gketenant-ns
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::443245368846:role/Devlift-PlatformAccess
  labels:
    app: gketenant-trial-mumbai-01-users
    app.kubernetes.io/name: gketenant-trial-mumbai-01-users
    app.kubernetes.io/instance: gketenant-trial-mumbai-01-users-stage
    app.kubernetes.io/managed-by: devlift
