apiVersion: v1
kind: ServiceAccount
metadata:
  name: devlift-trial-mumbai-01-navigation-sa
  namespace: nthelum-ns
  labels:
    app: devlift-trial-mumbai-01-navigation
    app.kubernetes.io/name: devlift-trial-mumbai-01-navigation
    app.kubernetes.io/instance: devlift-trial-mumbai-01-navigation-stage
    app.kubernetes.io/managed-by: devlift
