apiVersion: apps/v1
kind: Deployment
metadata:
  name: users
  namespace: users
  annotations:
    reloader.stakater.com/auto: 'true'
  labels:
    app: users
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      serviceAccountName: users-sa
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 2000
      containers:
        - name: users
          image: 443245368846.dkr.ecr.ap-south-1.amazonaws.com/users:IMAGE_TAG_PLACEHOLDER
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3333


          resources:
            requests:
              cpu: "1"
              memory: "1"
            limits:
              cpu: "1"
              memory: "1"
          livenessProbe:
            httpGet:
              path: /health
              port: 3333
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 3333
            initialDelaySeconds: 20
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 3

