apiVersion: v1
kind: ServiceAccount
metadata:
  name: first-sa
  namespace: default
  labels:
    app: first
    app.kubernetes.io/name: first
    app.kubernetes.io/instance: first-stage
    app.kubernetes.io/managed-by: devlift
