apiVersion: v1
kind: Service
metadata:
  name: first-service
  namespace: default
  labels:
    app: first
spec:
  type: ClusterIP
  selector:
    app: first
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    protocol: TCP
