apiVersion: v1
kind: ServiceAccount
metadata:
  name: users-sa
  namespace: default
  labels:
    app: users
    app.kubernetes.io/name: users
    app.kubernetes.io/instance: users-stage
    app.kubernetes.io/managed-by: devlift
